import { Theme, Agent, Language } from './types';

export const FLOWER_THEMES: Theme[] = [
    { name: "Lavender", colors: { primary: "#6B21A8" } },
    { name: "Rose", colors: { primary: "#BE123C" } },
    { name: "Sunflower", colors: { primary: "#D97706" } },
    { name: "Orchid", colors: { primary: "#86198F" } },
    { name: "Marigold", colors: { primary: "#EA580C" } },
    { name: "Lily", colors: { primary: "#4338CA" } },
    { name: "Tulip", colors: { primary: "#DC2626" } },
    { name: "Peony", colors: { primary: "#DB2777" } },
    { name: "Iris", colors: { primary: "#4F46E5" } },
    { name: "Hydrangea", colors: { primary: "#2563EB" } },
    { name: "Cherry Blossom", colors: { primary: "#EC4899" } },
    { name: "Daffodil", colors: { primary: "#FBBF24" } },
    { name: "Poppy", colors: { primary: "#EF4444" } },
    { name: "Bluebell", colors: { primary: "#3B82F6" } },
    { name: "Hibiscus", colors: { primary: "#E11D48" } },
    { name: "Jasmine", colors: { primary: "#65A30D" } },
    { name: "Lotus", colors: { primary: "#A21CAF" } },
    { name: "Magnolia", colors: { primary: "#FB7185" } },
    { name: "Periwinkle", colors: { primary: "#7C3AED" } },
    { name: "Zinnia", colors: { primary: "#F43F5E" } },
];

export const DEFAULT_AGENTS: Omit<Agent, 'id' | 'status' | 'output' | 'error' | 'outputJson' | 'model'>[] = [
    { name: 'Summary Agent', prompt: 'Summarize the following document in three key bullet points.' },
    { name: 'Sentiment Analyzer', prompt: 'Analyze the sentiment of the document. Respond with a single word: Positive, Negative, or Neutral. Then provide a brief justification. Format your response as a JSON object with keys "sentiment" and "justification".' },
    { name: 'Entity Extractor', prompt: 'Extract key entities (people, organizations, locations, dates) from the text. Return the result as a JSON array of objects, where each object has "name" and "type" keys.' },
    { name: 'Action Items Detector', prompt: 'Identify and list all potential action items or tasks mentioned in the document.' },
    { name: 'Fact Checker', prompt: 'Identify three key claims in the document that might need to be fact-checked. Do not perform the fact-check, just identify the claims.' },
];

export const MODEL_OPTIONS = [
    { value: 'gemini-2.5-flash', label: 'Gemini 2.5 Flash' },
    { value: 'gemini-flash-lite-latest', label: 'Gemini Flash Lite' },
];

export const LOCALIZATION: Record<Language, Record<string, string>> = {
    'en': {
        title: "CogniFlow Agentic System",
        settings: "Settings",
        style: "Style",
        language: "Language",
        mode: "Mode",
        apiKey: "API Key",
        apiKeySettings: "API Key Settings",
        apiKeyPrompt: "Your Gemini API Key is not set. Please provide one.",
        apiKeyInputPlaceholder: "Enter your Google AI Studio key",
        saveKey: "Save Key",
        close: "Close",
        documentControl: "Document",
        uploadDocument: "Upload Document",
        pasteContent: "Paste Content",
        pastePlaceholder: "Paste your text, markdown, json, or csv data here...",
        loadPastedContent: "Load Content",
        uploadHint: ".pdf, .txt, .md, .csv, .json",
        pdfViewer: "PDF Viewer",
        ocrSelectedPages: "OCR Selected Pages",
        ocrProcessing: "OCR Processing...",
        processedDocument: "Processed Document",
        addKeyword: "Add Keyword",
        keywordPlaceholder: "Enter keyword...",
        download: "Download",
        downloadMd: "Markdown",
        downloadPdf: "PDF",
        addAgent: "Add Agent",
        agentWorkflow: "Agent Workflow",
        runWorkflow: "Run Workflow",
        running: "Running...",
        addAgentToStart: "Add an agent from the panel to begin your workflow.",
        resultsDashboard: "Results Dashboard",
        runWorkflowToSeeResults: "Run a workflow to see the dashboard.",
        extractedEntities: "Extracted Entities",
        sentimentAnalysis: "Sentiment Analysis",
        followUpQuestions: "Suggested Follow-up Questions",
        error: "Error",
        noDocument: "No document loaded or processed yet.",
        loadingDocument: "Loading document...",
        clearAndReset: "Clear & Reset",
        fileSize: "Size",
        fileType: "Type",
    },
    'zh-TW': {
        title: "CogniFlow 代理AI系統",
        settings: "設定",
        style: "風格",
        language: "語言",
        mode: "模式",
        apiKey: "API 金鑰",
        apiKeySettings: "API 金鑰設定",
        apiKeyPrompt: "您的 Gemini API 金鑰尚未設定，請提供一個。",
        apiKeyInputPlaceholder: "輸入您的 Google AI Studio 金鑰",
        saveKey: "儲存金鑰",
        close: "關閉",
        documentControl: "文件",
        uploadDocument: "上傳文件",
        pasteContent: "貼上內容",
        pastePlaceholder: "在此處貼上您的文本、markdown、json 或 csv 數據...",
        loadPastedContent: "載入內容",
        uploadHint: ".pdf, .txt, .md, .csv, .json",
        pdfViewer: "PDF 檢視器",
        ocrSelectedPages: "OCR 選定頁面",
        ocrProcessing: "OCR 處理中...",
        processedDocument: "已處理文件",
        addKeyword: "新增關鍵字",
        keywordPlaceholder: "輸入關鍵字...",
        download: "下載",
        downloadMd: "Markdown",
        downloadPdf: "PDF",
        addAgent: "新增代理",
        agentWorkflow: "代理工作流程",
        runWorkflow: "執行工作流程",
        running: "執行中...",
        addAgentToStart: "從面板新增一個代理以開始您的工作流程。",
        resultsDashboard: "結果儀表板",
        runWorkflowToSeeResults: "執行工作流程以查看儀表板。",
        extractedEntities: "提取的實體",
        sentimentAnalysis: "情緒分析",
        followUpQuestions: "建議的後續問題",
        error: "錯誤",
        noDocument: "尚未載入或處理任何文件。",
        loadingDocument: "正在載入文件...",
        clearAndReset: "清除並重設",
        fileSize: "大小",
        fileType: "類型",
    }
};
